"""Repository package exports.

Expose the repository helper functions with friendly names so other modules
can import them from `src.backend.db.repositories`.
"""
from .person_repository import (
    find_people_by_neighborhood as find_people_by_neighborhood,
    find_people_by_ministry as find_people_by_ministry,
    find_people_by_name as find_people_by_name,
    find_all_people as find_all_people,
    find_person_by_id as find_person_by_id,
    delete_person as delete_person,
    create_person as create_person,
    update_person as update_person,
)
from .ministry_repository import get_area_and_ministry
from .config_repository import (
    get_all_ministries as get_all_ministries,
    get_ministry_by_id as get_ministry_by_id,
    create_ministry as create_ministry,
    update_ministry as update_ministry,
    delete_ministry as delete_ministry,
    get_all_areas as get_all_areas,
    get_areas_by_ministry as get_areas_by_ministry,
    get_area_by_id as get_area_by_id,
    create_area as create_area,
    update_area as update_area,
    delete_area as delete_area,
    get_all_consolidations as get_all_consolidations,
    get_consolidation_by_id as get_consolidation_by_id,
    create_consolidation as create_consolidation,
    update_consolidation as update_consolidation,
    delete_consolidation as delete_consolidation,
    get_all_cdb_options as get_all_cdb_options,
    get_cdb_by_id as get_cdb_by_id,
    create_cdb as create_cdb,
    update_cdb as update_cdb,
    delete_cdb as delete_cdb,
)

__all__ = [
    "find_people_by_neighborhood",
    "find_people_by_ministry",
    "find_people_by_name",
    "find_all_people",
    "find_person_by_id",
    "delete_person",
    "create_person",
    "update_person",
    "get_area_and_ministry",
    "get_all_ministries",
    "get_ministry_by_id",
    "create_ministry",
    "update_ministry",
    "delete_ministry",
    "get_all_areas",
    "get_areas_by_ministry",
    "get_area_by_id",
    "create_area",
    "update_area",
    "delete_area",
    "get_all_consolidations",
    "get_consolidation_by_id",
    "create_consolidation",
    "update_consolidation",
    "delete_consolidation",
    "get_all_cdb_options",
    "get_cdb_by_id",
    "create_cdb",
    "update_cdb",
    "delete_cdb",
]
